### PR TITLE
decoded images

### PR DESCRIPTION
**Pull request by YASMIN-SEKH**
Issue: #51 

Short description of what this resolves: 
- Decoded both images provided in the issue

Changes proposed in this pull request and/or Screenshots of changes:
-first qr code is saved as img1.png and the second is saved as img2.txt
- install requirements.txt

Screenshot 2024-12-22 235442
Screenshot 2024-12-22 235421
Screenshot 2024-12-22 235557
Screenshot 2024-12-24 000539
Screenshot 2024-12-24 000857

### CODE REVIEW

**Comment by Shivg2901** [comment]
@YASMIN-SEKH 
Screenshot 2024-12-23 at 10 03 55 AM
Kindly look into this

**Comment by Shivg2901** [comment]
@YASMIN-SEKH 
Could you upload the output of the qr with the image and also screenshot of the shell or terminal you are running it in

**Comment by YASMIN-SEKH** [comment]
> @YASMIN-SEKH Could you upload the output of the qr with the image and also screenshot of the shell or terminal you are running it in

Hey, I have added the screenshots.

**Comment by shauryaaa100** [comment]
@YASMIN-SEKH 
I have tried running your program, but it is still not detecting any qr. Can you clarify how you decoded the test QRs in that case, since your program is not running?
image

**Pull request merged**
