### PR TITLE
Made a QR Encoder using Node.js

### PR DESCRIPTION
**Pull request by krishnamohan2006**
Issue: #5 
Created a QR Encoder using Node.js
Screenshot (268)

### CODE REVIEW

**Comment by Shivg2901** [comment]
@krishnamohan2006 
screenshots of relevant inputs and outputs
also mention what file forms you support

**Comment by Shivg2901** [comment]
@krishnamohan2006 
text should be displayed as text
i wrote hello in input file
output is this
IMG_A066DE3E3300-1

**Comment by krishnamohan2006** [comment]
Issue: #1 
Screenshot (269)

**Comment by krishnamohan2006** [comment]
@Shivg2901 Now check, I modified and now the QR will show the exact text encoded in it.

**Comment by Shivg2901** [comment]
good job!

**Pull request merged**
