### PR TITLE
Decoder done

### PR DESCRIPTION
**Pull request by Darkknight0125**
Issue: #51 

Added the script and output files.

SS-1
out1 (2)
Screenshot (270)

SS-2
out2 (2)
Screenshot (271)

### CODE REVIEW

**Comment by shauryaaa100** [comment]
@Darkknight0125 
The extension for the file inside the first QR is .png. 
Sorry, it wasn't mentioned in the issue. 
So please run the script again for the 1st QR, by inputting the output file name with extension. And attach the ss showing the image.
Then I'll merge this PR.

**Comment by Darkknight0125** [comment]
@shauryaaa100 the output is not a viewable png, Is my decoder wrong or is the file like that only, is it just binary?
Please check.

**Comment by shauryaaa100** [comment]
@Darkknight0125 
I think the problem can be in line 20 of your code. You have used utf-8 decoder there, which I think was not required at the initial step. Try fixing that, and check.

**Comment by shauryaaa100** [comment]
Or maybe it can be because the binary file contains spaces. You can try by removing the spaces.

**Comment by Darkknight0125** [comment]
@shauryaaa100  Made the changes and have valid output, please review.

**Pull request merged**
